export const watchlist = [
  {
    title: 'Schmigadoon!',
    imdbId: 'tt11808942',
    status: 2,
    service: 4,
    poster: 'https://m.media-amazon.com/images/M/MV5BN2Q4MzMwYjUtNGM3NC00NGU3LTgxY2YtMjJiNDFiOGU4MmNjXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'Behind the Attraction',
    imdbId: 'tt11069436',
    status: 1,
    service: 0,
    poster: 'https://m.media-amazon.com/images/M/MV5BYjQ2ODg3MjktZDc2OC00YTY1LWEwMzEtZWE0YmYxZmJkOWI1XkEyXkFqcGdeQXVyMTQ2Nzc5Ng@@._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'Vicious Circle',
    imdbId: 'tt0867149',
    status: 0,
    service: 'AppleTV',
    poster: 'https://m.media-amazon.com/images/M/MV5BMTgwNDkzNTk4MF5BMl5BanBnXkFtZTcwMzQ3NjgzMQ@@._V1_SX300.jpg',
    type: 2,
  },
  {
    title: 'What if?',
    imdbId: 'tt10168312',
    status: 1,
    service: 0,
    poster: 'https://m.media-amazon.com/images/M/MV5BOGYwYTA5M2QtMTk3Zi00ZjdjLWFkNDUtYzg4MjM0ZGI0MGU1XkEyXkFqcGdeQXVyODIyOTEyMzY@._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'The Sound With Mark Ronson',
    imdbId: 'tt14482570',
    status: 0,
    service: 4,
    poster: 'https://m.media-amazon.com/images/M/MV5BY2YyM2I3NmYtZTk5Zi00M2QwLWFmMTMtNTIyYmVmZDc5NDFlXkEyXkFqcGdeQXVyMDU5MDEyMA@@._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'Only Murders in the Building',
    imdbId: 'tt12851524',
    status: 1,
    service: 6,
    poster: 'https://m.media-amazon.com/images/M/MV5BODAzZjI5NGItNGNlYS00NWU1LTgwNjUtOGQwNWJiMWQwMDg1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'See',
    imdbId: 'tt7949218',
    status: 0,
    service: 4,
    poster: 'https://m.media-amazon.com/images/M/MV5BM2JkM2Y5NTEtZWIwZS00ZTliLTk3MDMtNzY4MDNkNjg0NTkwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'The Boys',
    imdbId: 'tt1190634',
    status: 1,
    service: 2,
    poster: 'https://m.media-amazon.com/images/M/MV5BNGEyOGJiNWEtMTgwMi00ODU4LTlkMjItZWI4NjFmMzgxZGY2XkEyXkFqcGdeQXVyNjcyNjcyMzQ@._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'Mr. Corman',
    imdbId: 'tt10971064',
    status: 0,
    service: 4,
    poster: 'https://m.media-amazon.com/images/M/MV5BZWRmNDRiZWQtMTE1My00ZmQzLWJkMTAtYzY5NGY2Y2RkYTNiXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'Monsters at Work',
    imdbId: 'tt8610082',
    status: 1,
    service: 0,
    poster: 'https://m.media-amazon.com/images/M/MV5BOWI4OWE5MDgtMGNlYi00N2MwLWJlZmQtNGJlMjU4OGVkZjFmXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'Turner & Hooch',
    imdbId: 'tt11547014',
    status: 0,
    service: 0,
    poster: 'https://m.media-amazon.com/images/M/MV5BYzdhODc3OTctODc2ZS00MjIxLWIxMzAtY2M0M2UwMjFiNzNhXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'The White Lotus',
    imdbId: 'tt13406094',
    status: 2,
    service: 5,
    poster: 'https://m.media-amazon.com/images/M/MV5BOWY1YjY1MWUtYWY5Yi00YTM4LTkyM2UtMDQ3NmFiYTkyYjlkXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'Vivo',
    imdbId: 'tt6338498',
    status: 2,
    service: 1,
    poster: 'https://m.media-amazon.com/images/M/MV5BNDBiMGEzMTAtYTI2MS00NTgyLTlhNTItNmJiOTdhZTMyOTI1XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg',
    type: 0,
  },
  {
    title: 'The Mysterious Benedict Society',
    imdbId: '',
    status: 0,
    service: 0,
    poster: '',
    type: 1,
  },
  {
    title: 'Short Circuit',
    imdbId: '',
    status: 0,
    service: 0,
    poster: '',
    type: 1,
  },
  {
    title: 'The Swiss Family Robinson',
    imdbId: '',
    status: 0,
    service: 0,
    poster: '',
    type: 0,
  },
  {
    title: 'Avatar',
    imdbId: '',
    status: 0,
    service: 3,
    poster: '',
    type: 0,
  },
  {
    title: 'Arrested Development',
    imdbId: 'tt0367279',
    status: 1,
    service: 6,
    poster: 'https://m.media-amazon.com/images/M/MV5BNTFlYTE2YTItZmQ1NS00ZWQ5LWI3OGUtYTQzNDMyZmEyYTZjXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'Nine Perfect Strangers',
    imdbId: '',
    status: 1,
    service: 6,
    poster: '',
    type: 1,
  },
  {
    title: 'Suicide Squad',
    imdbId: '',
    status: 0,
    service: 5,
    poster: '',
    type: 0,
  },
  {
    title: 'Mortal Combat',
    imdbId: 'tt0293429',
    status: 0,
    service: 5,
    poster: 'https://m.media-amazon.com/images/M/MV5BY2ZlNWIxODMtN2YwZi00ZjNmLWIyN2UtZTFkYmZkNDQyNTAyXkEyXkFqcGdeQXVyODkzNTgxMDg@._V1_SX300.jpg',
    type: 0,
  },
  {
    title: 'Foundation',
    imdbId: '',
    status: 0,
    service: 4,
    poster: '',
    type: 1,
  },
  {
    title: 'My Unorthodox Life',
    imdbId: 'tt14398500',
    status: 0,
    service: 1,
    poster: 'https://m.media-amazon.com/images/M/MV5BM2QzNzFkODYtNmM0Ni00ZDdlLWJiOWYtZDIzNmExNWYzMTUyXkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'Trailer: The Eternals',
    imdbId: 'tt9032400',
    status: 2,
    service: 7,
    poster: 'https://m.media-amazon.com/images/M/MV5BMTExZmVjY2ItYTAzYi00MDdlLWFlOWItNTJhMDRjMzQ5ZGY0XkEyXkFqcGdeQXVyODIyOTEyMzY@._V1_SX300.jpg',
    type: 5,
  },
  {
    title: 'Electric Dreams',
    imdbId: '',
    status: 1,
    service: 2,
    poster: '',
    type: 1,
  },
  {
    title: 'Spider-Man: Homecoming',
    imdbId: '',
    status: 0,
    service: 0,
    poster: '',
    type: 0,
  },
  {
    title: 'Spider-Man: Far From Home',
    imdbId: '',
    status: 0,
    service: 0,
    poster: '',
    type: 0,
  },
  {
    title: 'Let Him Go',
    imdbId: '',
    status: 0,
    service: 5,
    poster: '',
    type: 0,
  },
  {
    title: 'The Little Things',
    imdbId: '',
    status: 0,
    service: 5,
    poster: '',
    type: 0,
  },
  {
    title: 'Coming to America',
    imdbId: '',
    status: 0,
    service: 'AppleTV',
    poster: '',
    type: 0,
  },
  {
    title: 'Coming 2 America',
    imdbId: '',
    status: 0,
    service: 2,
    poster: '',
    type: 0,
  },
  {
    title: 'The Aeronauts',
    imdbId: 'tt6141246',
    status: 0,
    service: 2,
    poster: 'https://m.media-amazon.com/images/M/MV5BMmJkM2M0OTUtNGI3NC00ZTNiLWI4MDUtMGI5MzM1MmQyNTliXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg',
    type: 0,
  },
  {
    title: 'Mud',
    imdbId: 'tt1935179',
    status: 0,
    service: 'AppleTV',
    poster: 'https://m.media-amazon.com/images/M/MV5BMTU2MzcyODgyNV5BMl5BanBnXkFtZTcwNTc4MDYwOQ@@._V1_SX300.jpg',
    type: 0,
  },
  {
    title: 'Sweet Girl',
    imdbId: 'tt10731768',
    status: 0,
    service: 1,
    poster: 'https://m.media-amazon.com/images/M/MV5BOGIzOTZiZjItNTMyYS00ODcyLWE2ZDUtYWNjZDNmNTUxYjVkXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg',
    type: 0,
  },
  {
    title: 'Beckett',
    imdbId: 'tt10230994',
    status: 0,
    service: 1,
    poster: 'https://m.media-amazon.com/images/M/MV5BYmVlNWJkZWYtYmJkMy00YTZlLTgwODMtZjVmOGMzMmM1ZTk2XkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_SX300.jpg',
    type: 0,
  },
  {
    title: 'Top Secret UFO Projects: Declassified',
    imdbId: 'tt14992232',
    status: 2,
    service: 1,
    poster: 'https://m.media-amazon.com/images/M/MV5BNTU4OGY2YmYtMjc1NC00NWVjLTkyMDctOTI4YzNkOTFhYTg3XkEyXkFqcGdeQXVyODQwOTE4MDg@._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'The Woman in the Window',
    imdbId: 'tt6111574',
    status: 0,
    service: 1,
    poster: 'https://m.media-amazon.com/images/M/MV5BYmVlNWJkZWYtYmJkMy00YTZlLTgwODMtZjVmOGMzMmM1ZTk2XkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_SX300.jpg',
    type: 0,
  },
  {
    title: 'Stuntman',
    imdbId: 'tt6539830',
    status: 0,
    service: 0,
    poster: 'https://m.media-amazon.com/images/M/MV5BNzcyNjc5NTItNDA3OC00MGViLWI4N2UtMzY1ODU5NmQwODU4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
    type: 4,
  },
  {
    title: '22 Versus Earth',
    imdbId: 'tt14499632',
    status: 0,
    service: 0,
    poster: 'https://m.media-amazon.com/images/M/MV5BNTk5YTcwYzktZWU0Yy00YmZiLWJlZGQtZDQ1ZjIwOTFkMDQzXkEyXkFqcGdeQXVyMTE5NDQ1MzQ3._V1_SX300.jpg',
    type: 0,
  },
  {
    title: 'Launchpad Short Films',
    imdbId: 'tt14465474',
    status: 0,
    service: 0,
    poster: 'https://m.media-amazon.com/images/M/MV5BOTEzZWY3ZDgtZTQ0Ni00MzEzLTg1MDgtNDFiMTNhZDJhMjY2XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'Inside Pixar',
    imdbId: 'tt13302848',
    status: 0,
    service: 0,
    poster: 'https://m.media-amazon.com/images/M/MV5BYmY1ZTU0ODUtNzRkMy00MmM0LWFhOTYtMWE5OTE4MmJhZjZhXkEyXkFqcGdeQXVyODQ4MjU1MDk@._V1_SX300.jpg',
    type: 4,
  },
  {
    title: 'Bill & Ted Face the Music',
    imdbId: 'tt1086064',
    status: 0,
    service: 2,
    poster: 'https://m.media-amazon.com/images/M/MV5BOTRiNzFhNjAtNTdhMS00ZjViLWFhNTUtMWJlMTJkMGM1YzM4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
    type: 0,
  },
  {
    title: 'Ted Lasso',
    imdbId: 'tt10986410',
    status: 1,
    service: 4,
    poster: 'https://m.media-amazon.com/images/M/MV5BZTRhNzg0ZTgtZmMyYy00Yjc5LTkyNTAtNzEzODIyZDE5NTNmXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'Tiny World',
    imdbId: 'tt13007904',
    status: 0,
    service: 4,
    poster: 'https://m.media-amazon.com/images/M/MV5BOWI4NjhkM2QtNTYyZi00ODA1LWFkNWEtZmEyOGZiNTg3ZmZjXkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_SX300.jpg',
    type: 4,
  },
  {
    title: 'Reminiscence',
    imdbId: 'tt3272066',
    status: 0,
    service: 5,
    poster: 'https://m.media-amazon.com/images/M/MV5BODBkMTNmMmQtYTNlMy00OTRhLWE5MzgtYTZlMTUyYzY1MzkzXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_SX300.jpg',
    type: 0,
  },
  {
    title: 'Star Wars: Biomes',
    imdbId: 'tt14578676',
    status: 2,
    service: 0,
    poster: 'https://m.media-amazon.com/images/M/MV5BMmI1ODIxOTItMDYzMy00NGM2LWFlN2YtODBiZWFkMWIzOWExXkEyXkFqcGdeQXVyODQ4MjU1MDk@._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'Star Wars: Vehicle Fly Throughs',
    imdbId: 'tt14578626',
    status: 2,
    service: 0,
    poster: 'https://m.media-amazon.com/images/M/MV5BNTg4ZmM4ZjItYTBiMy00NmQ3LWIyNWEtZDViOGQwMjJhOWNlXkEyXkFqcGdeQXVyMDM0MzU2NA@@._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'Wind River',
    imdbId: 'tt5362988',
    status: 0,
    service: 1,
    poster: 'https://m.media-amazon.com/images/M/MV5BMTUyMjU1OTUwM15BMl5BanBnXkFtZTgwMDg1NDQ2MjI@._V1_SX300.jpg',
    type: 0,
  },
  {
    title: 'Midnight Mass',
    imdbId: 'tt10574558',
    status: 0,
    service: 1,
    poster: 'https://m.media-amazon.com/images/M/MV5BODFiYjI3Y2UtY2M5My00ODk3LTgwN2MtOTg5MDFhYjBmMmQ3XkEyXkFqcGdeQXVyNjY0MzEwMTY@._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'Vacation Friends',
    imdbId: 'tt3626476',
    status: 0,
    service: 6,
    poster: 'https://m.media-amazon.com/images/M/MV5BZmI0YTY4YTYtODk4MS00ZWE3LWJjYzUtODAwOWM5YWY4MWUwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg',
    type: 0,
  },
  {
    title: 'Muppets Haunted Mansion',
    imdbId: 'tt14602326',
    status: 0,
    service: 0,
    poster: 'https://m.media-amazon.com/images/M/MV5BNDYwMGI4ZTctZTgwNC00YmRmLThjODQtYjNjMzNkMTdhYTQzXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_QL75_UY562_CR35,0,380,562_.jpg',
    type: 2,
  },
  {
    title: 'Don\'t Look Up',
    imdbId: 'tt11286314',
    status: 0,
    service: 1,
    poster: 'https://m.media-amazon.com/images/M/MV5BN2ZhMzMzNWEtZThlOS00MzU1LTgwMGQtMGI4ZWU0OTEzMTM3XkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_SX300.jpg',
    type: 0,
  },
  {
    title: 'Close Encounters of the Fifth Kind',
    imdbId: 'tt12108272',
    status: 2,
    service: 2,
    poster: 'https://m.media-amazon.com/images/M/MV5BM2UwNzUxMmEtMDI5OS00ODZmLWJmYzUtYjE4NjA3OGNlODJhXkEyXkFqcGdeQXVyMTE2NzYwOTI5._V1_SX300.jpg',
    type: 4,
  },
  {
    title: 'Star Wars Visions',
    imdbId: 'tt13622982',
    status: 0,
    service: 0,
    poster: 'https://m.media-amazon.com/images/M/MV5BNmFiZDM3M2ItMGY5OS00ZGU2LTlkMmYtNTRiZDE0OWI0MTRiXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg',
    type: 1,
  },
  {
    title: 'Just Beyond',
    imdbId: 'tt12286434',
    status: 0,
    service: 0,
    poster: 'https://m.media-amazon.com/images/M/MV5BOTUyNzJiMWMtNzcxYS00ZjYyLTllODctODJjZGFjOWRiNWUzXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_QL75_UY562_CR36,0,380,562_.jpg',
    type: 1,
  },
  {
    title: 'Afterlife of the Party',
    imdbId: 'tt11742798',
    status: 0,
    service: 1,
    poster: 'https://m.media-amazon.com/images/M/MV5BN2FlMGRlZTctY2Q5YS00ZWIzLThjYzQtNTZhYmEwYjU2MmI0XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg',
    type: 0,
  },
  {
    title: 'Count Me In',
    imdbId: 'tt6889042',
    status: 0,
    service: 1,
    poster: 'https://m.media-amazon.com/images/M/MV5BOGI1NTQxM2ItNDFkMi00OGY3LTljMGYtZmY5OTdlZjIxNmE4XkEyXkFqcGdeQXVyMjM4NzgxMw@@._V1_SX300.jpg',
    type: 0,
  },
];
